---
- name: Docker Installation
  hosts: {{ HOSTS }} 
  remote_user: cddeploy
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - docker_install/vars/root_password.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"
  roles:
    - role: docker_install