---
- name: Docker Installation
  hosts: app_prod
  remote_user: cddeploy
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - root_password.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"

  tasks:
    - name: Create a directory under home
      file:
        path: /opt/docker
        state: directory
        mode: '0755'
        
    - name: This command will change the working directory to somedir/
      shell:
        cmd: curl -fsSL https://get.docker.com -o install-docker.sh
        chdir: /home/cddeploy/app/docker
    
    - name: This command will change the working directory to somedir/
      shell:
        cmd: sudo sh install-docker.sh
        chdir: /home/cddeploy/app/docker

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
