---
- name: Docker Installation
  hosts: app_prod
  remote_user: cddeploy
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - root_password.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"
    docker_installation: "/opt/docker"

  tasks:
    - name: Create docker directory
      file:
        path: "{{ docker_installation }}"
        state: directory
        mode: '0755'
    
    - name: install package
      package:
        name: "{{ package }}"
        state: present
        
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
