---
- name: Docker Installation
  hosts: app_prod
  remote_user: cddeploy
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - root_password.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"
    docker_installation: "/opt/docker"
    package: "docker"

  tasks:
    - name: Create docker directory
      file:
        path: "{{ docker_installation }}"
        state: directory
        mode: '0755'
    
    - name: Install Docker if not present
      package:
        name: "{{ package }}"
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the courier_management image
      tags: deploy
      community.docker.docker_image:
        name: courier_mgmt
        repository: 192.168.0.130:5000/courier_mgmt:latest
        source: pull
      delegate_to: localhost
      vars:
        ansible_python_interpreter: /usr/bin/python3