---
- name: Docker Installation
  hosts: app_prod
  remote_user: cddeploy
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - root_password.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"
    docker_installation: "/opt/docker"

  tasks:
    - name: Create docker directory
      file:
        path: "{{ docker_installation }}"
        state: directory
        mode: '0755'
    
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: yes
    
    - name: Debug Docker Output
      debug:
        var: docker_check

    - name: Get Docker engine
      shell:
        cmd: curl -fsSL https://get.docker.com -o install-docker.sh
        chdir: "{{ docker_installation }}"
      when: docker_check.failed

    - name: Install Docker
      shell:
        cmd: sudo sh install-docker.sh
        chdir: "{{ docker_installation }}"
      when: not docker_check.failed

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
